### ISSUE TITLE
Unable to connect electrumx server to bitcoind daemon

### ISSUE THREAD

**Issue by ElderBlade** [willcl-ark/bitcoin-core-docker#26]
I'm running electrumx from this image https://github.com/lukechilds/docker-electrumx, and I cannot get my server to connect to bitcoind in my podman container. I was able to connect to bitcoind v25 that's running bare metal on a raspberry pi.

This may not be an issue specific to this container image but figured I would ask for help in getting the connection to work.

my docker-compose bitcoind:
```yaml
version: '3'
services:
  bitcoin-core:
    image: bitcoin/bitcoin:latest
    container_name: bitcoin-core
    ports:
      - "8332:8332" # RPC port
      - "8333:8333" # P2P port
    volumes:
      - /mnt/bitcoin:/home/bitcoin/.bitcoin:Z
      - /home/ElderBlade/Projects/podman/bitcoin-core/bitcoin.conf:/root/.bitcoin/bitcoin.conf:Z
    networks:
      - bitcoin_net

networks:
  bitcoin_net:
    name: bitcoin_net
    external: true
```

bitcoin.conf
```
txindex=1
server=1
maxuploadtarget=400
rest=1

[main]
rpcbind=127.0.0.1
rpcbind=192.168.1.130
rpcbind=10.89.12.3

rpcallowip=127.0.0.1
rpcallowip=192.168.1.0/16
rpcallowip=10.89.12.0/24

rpcauth=<user>:<long hash pwd>

electrumx docker-compose
```yaml
version: '3'

services:
  electrumx:
    image: lukechilds/electrumx
    container_name: electrumx
    ports:
      - "50002:50002"
    volumes:
      - /mnt/electrumx:/data:Z
    environment:
      - DAEMON_URL=http://<user>:<password>@192.168.1.130:8332
      - COIN=Bitcoin
      - PEER_DISCOVER=off
      - COST_SOFT_LIMIT=0
      - COST_HARD_LIMIT=0
    networks:
      bitcoin_net:
        ipv4_address: 10.89.12.3
    restart: unless-stopped

networks:
  bitcoin_net:
    name: bitcoin_net
    external: true
    ipam:
      config:
        - subnet: 10.89.1.0/24
          gateway: 10.89.1.1
```

I'm running these containers on Fedora Server 40.

I have verified ports are open on my host, and I also enabled http traffic for port 8332 in my SELinux policy. I simply get connection refused error both in electrumx server and in my host terminal when I run `curl --user <user>:<password> --data '{"method": "getinfo"}' http://localhost:8332`

Any suggestions to resolve this?
